---
##############################################################################
# Atlas Configuration
##############################################################################
atlas:
  enabled: true